# Generated by cucumber-sinatra. (2015-08-06 07:31:26 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/story_writer.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = StoryWriter

class StoryWriterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  StoryWriterWorld.new
end
